### ISSUE TITLE
Rust

### ISSUE THREAD

**Issue by xxscloud5722** [zsiciarz/rust-cpuid#10]
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-arch" "x86_64" "-L" "/Users/xxscloud/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/xxscloud/code/c_/rust_demo_1/target/debug/deps/rust_demo_1.1ml7kh6hdorzv4uc.rcgu.o" "/Users/xxscloud/code/c_/rust_demo_1/target/debug/deps/rust_demo_1.1pb8ejs1o3cmfeql.rcgu.o" "/Users/xxscloud/code/c_/rust_demo_1/target/debug/deps/rust_demo_1.2306boujys9szdux.rcgu.o" "/Users/xxscloud/code/c_/rust_demo_1/target/debug/deps/rust_demo_1.2ek5u3n63apza2a3.rcgu.o" "/Users/xxscloud/code/c_/rust_demo_1/target/debug/deps/rust_demo_1.2r94wn78hvn4zfa0.rcgu.o" "/Users/xxscloud/code/c_/rust_demo_1/target/debug/deps/rust_demo_1.2uw6fbkw9d9sus03.rcgu.o" "/Users/xxscloud/code/c_/rust_demo_1/target/debug/deps/rust_demo_1.36by2ghrjym8hwve.rcgu.o" "/Users/xxscloud/code/c_/rust_demo_1/target/debug/deps/rust_demo_1.4zs35g4vxee7dugd.rcgu.o" "/Users/xxscloud/code/c_/rust_demo_1/target/debug/deps/rust_demo_1.a3ytjr85nc43ftt.rcgu.o" "/Users/xxscloud/code/c_/rust_demo_1/target/debug/deps/rust_demo_1.b2z0z0tyc2cedm9.rcgu.o" "/Users/xxscloud/code/c_/rust_demo_1/target/debug/deps/rust_demo_1.e2qp815mh3ld0ff.rcgu.o" "/Users/xxscloud/code/c_/rust_demo_1/target/debug/deps/rust_demo_1.p6tmp85ygvu9c8.rcgu.o" "-o" "/Users/xxscloud/code/c_/rust_demo_1/target/debug/deps/rust_demo_1" "/Users/xxscloud/code/c_/rust_demo_1/target/debug/deps/rust_demo_1.51uk62vzlfmw7lm0.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/xxscloud/code/c_/rust_demo_1/target/debug/deps" "-L" "/Users/xxscloud/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/xxscloud/code/c_/rust_demo_1/target/debug/deps/libcpuid-b22617789c26c4e2.rlib" "/Users/xxscloud/code/c_/rust_demo_1/target/debug/deps/liblibc-7defa6ebacb6b9fc.rlib" "/Users/xxscloud/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-688c1376a25c049d.rlib" "/Users/xxscloud/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-078f89c2cdb6d46b.rlib" "/Users/xxscloud/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libobject-fec020208bc1ad3c.rlib" "/Users/xxscloud/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libaddr2line-38540dcacc9fd218.rlib" "/Users/xxscloud/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libgimli-6f613179f618c598.rlib" "/Users/xxscloud/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_demangle-4d1a5d7118aaeaf2.rlib" "/Users/xxscloud/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libhashbrown-d88fab3b1b9d8356.rlib" "/Users/xxscloud/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_alloc-a21754532a052f2f.rlib" "/Users/xxscloud/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-2e9ebc4127641a96.rlib" "/Users/xxscloud/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcfg_if-82d0f961232a05ca.rlib" "/Users/xxscloud/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-370b1b71f08bac3c.rlib" "/Users/xxscloud/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-816106c1f35f5421.rlib" "/Users/xxscloud/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-20f3a030f1a56a86.rlib" "/Users/xxscloud/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-60333aa00936c5ce.rlib" "/Users/xxscloud/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-116aaeaea873ef94.rlib" "-lcpuid" "-lSystem" "-lresolv" "-lc" "-lm"
  = note: ld: library not found for -lcpuid
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by abronan** [comment]
You need to install **libcpuid** on your system. Look for a readily available package if you use apt-get or install it from sources following the README at https://github.com/anrieff/libcpuid
