### ISSUE TITLE
Documentation Link

### ISSUE THREAD

**Issue by william20111** [zsiciarz/rust-cpuid#8]
The docs link forwarded to me a NSFW website. I only came here for a cpuid lib.....

Not sure what the deal is with that but getting it changed would be great. And maybe onto rusts official docs site. 

Cheers
Will

**Comment by zsiciarz** [comment]
Hey Will, thanks for the report! The link was... unfortunate :( looks like rust-ci.org no longer exists. I've updated the readme to point to docs.rs in 882bb0f. Hope this helps!

**Comment by william20111** [comment]
Its no bother. Just caught me off guard ha! Thanks for the quick response.
